on:
  schedule:
  - cron: '*/5 * * * *' # Runs at 00:00 every Saturday and Sunday
workflow_dispatch:

# Define the jobs to be executed within the workflow
jobs:
  build:
  # Specify the runner environment
  runs-on: ubuntu-latest
  steps:
  
  # Step 1: Checkout the repository content
  - name: checkout repo content
    uses: actions/checkout@v2 # Checkout the repository content to GitHub runner
  
  # Step 2: Setup Python
  - name: setup python
    uses: actions/setup-python@v4
    with:
    python-version: '3.12' # Install the specified Python version
  
  # Step 3: Install Python packages
  - name: install python packages
    run: | 
      python -m pip install --upgrade pip
      pip install -r requirements.txt
  
  # Step 4: Execute extract script
  - name: execute extract script
    env:
  # Set environment variable from GitHub secrets
    BLOB_STORAGE_CONN_STR : ${{ secrets.BLOB_STORAGE_CONN_STR }} 
    BLOB_STORAGE_CNTR : ${{ secrets.BLOB_STORAGE_CNTR }}
    PSG_USR : ${{ secrets.PSG_USR }}
    PSG_HOST : ${{ secrets.PSG_HOST }}
    PSG_PORT : ${{ secrets.PSG_PORT }}
    PSG_DBN : ${{ secrets.PSG_DBN }}
    PSG_PSWD : ${{ secrets.PSG_PSWD }}
    run: python main.py # Run the 'main.py' script
