on:
  schedule:
    - cron: '0 0 * * 0' # Runs every day at 12 AM
  workflow_dispatch:

# Define the jobs to be executed within the workflow
jobs:
  build:
    # Specify the runner environment
    runs-on: ubuntu-latest
    steps:
    
      # Step 1: Checkout the repository content
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to GitHub runner
      
      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Install the specified Python version
      
      # Step 3: Install Python packages
      - name: Install Python packages
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 4: Execute extract script
      - name: Execute extract script
        env:
          # Set environment variables from GitHub secrets
          BLOB_STORAGE_CONN_STR: ${{ secrets.BLOB_STORAGE_CONN_STR }} 
          BLOB_STORAGE_CNTR: ${{ secrets.BLOB_STORAGE_CNTR }}
          PSG_USR: ${{ secrets.PSG_USR }}
          PSG_HOST: ${{ secrets.PSG_HOST }}
          PSG_PORT: ${{ secrets.PSG_PORT }}
          PSG_DBN: ${{ secrets.PSG_DBN }}
          PSG_PSWD: ${{ secrets.PSG_PSWD }}
        run: python main.py # Run the 'main.py' script
